# Generated by Django 5.0 on 2024-01-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduleStudents', '0003_remove_student_file_remove_student_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('top_speed', models.IntegerField(default=45)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
